# Generated by Django 3.2.5 on 2021-07-21 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competicao',
            options={'verbose_name': 'Competicao', 'verbose_name_plural': 'Competicoes'},
        ),
        migrations.AlterModelOptions(
            name='estadio',
            options={'verbose_name': 'Estadio', 'verbose_name_plural': 'Estadios'},
        ),
        migrations.AlterModelOptions(
            name='partida',
            options={'verbose_name': 'Partida', 'verbose_name_plural': 'Partidas'},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'verbose_name': 'Time', 'verbose_name_plural': 'Times'},
        ),
    ]
