# Generated by Django 3.2.5 on 2021-07-23 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0002_auto_20210721_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competicao',
            options={'verbose_name': 'Competição', 'verbose_name_plural': 'Competições'},
        ),
        migrations.AlterModelOptions(
            name='estadio',
            options={'verbose_name': 'Estádio', 'verbose_name_plural': 'Estádios'},
        ),
        migrations.RemoveField(
            model_name='partida',
            name='quantidade_periodos_extra',
        ),
        migrations.AddField(
            model_name='partida',
            name='teve_periodo_extra',
            field=models.BooleanField(default=False, verbose_name='Houve Período Extra?'),
        ),
        migrations.AlterField(
            model_name='competicao',
            name='data_final',
            field=models.DateField(verbose_name='Final da Competição'),
        ),
        migrations.AlterField(
            model_name='competicao',
            name='data_inicio',
            field=models.DateField(verbose_name='Início da Competição'),
        ),
        migrations.AlterField(
            model_name='competicao',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome da Competição'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='competicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jogos.competicao', verbose_name='Competição'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='link_video',
            field=models.URLField(blank=True, verbose_name='Vídeo da Partida'),
        ),
    ]
