# Generated by Django 3.2.5 on 2021-07-23 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0003_auto_20210722_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competicao',
            name='esta_em_andamento',
        ),
        migrations.AddField(
            model_name='competicao',
            name='esta_ativa',
            field=models.BooleanField(default=True, verbose_name='Está Ativa?'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='competicao',
            field=models.ForeignKey(limit_choices_to={'esta_ativa': True}, on_delete=django.db.models.deletion.PROTECT, to='jogos.competicao', verbose_name='Competição'),
        ),
    ]
