# Generated by Django 3.2.5 on 2021-07-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0005_auto_20210723_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='esta_ativo',
            field=models.BooleanField(default=True, verbose_name='Está Ativo?'),
        ),
    ]
