# Generated by Django 3.2.5 on 2021-07-23 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=20, verbose_name='Sigla')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Falta')),
            ],
            options={
                'verbose_name': 'Falta',
                'verbose_name_plural': 'Faltas',
            },
        ),
        migrations.CreateModel(
            name='Penalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_da_falta', models.CharField(choices=[('1Q', '1º Quarto'), ('2Q', '2º Quarto'), ('3Q', '3º Quarto'), ('4Q', '4º Quarto'), ('EX', 'Período Extra')], default='1Q', max_length=2, verbose_name='Periodo de Jogo')),
                ('falta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faltas.falta', verbose_name='Falta Cometida')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogos.partida', verbose_name='Partida')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogos.time', verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Penalidade',
                'verbose_name_plural': 'Penalidades',
            },
        ),
    ]
