# Generated by Django 3.2.5 on 2021-07-21 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faltas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='falta',
            options={'verbose_name': 'Falta', 'verbose_name_plural': 'Faltas'},
        ),
        migrations.AlterModelOptions(
            name='penalidade',
            options={'verbose_name': 'Penalidade', 'verbose_name_plural': 'Penalidades'},
        ),
    ]
