# Generated by Django 3.2.5 on 2021-07-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faltas', '0002_auto_20210721_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penalidade',
            name='periodo',
        ),
        migrations.AddField(
            model_name='penalidade',
            name='periodo_da_falta',
            field=models.CharField(choices=[('1Q', '1º Quarto'), ('2Q', '2º Quarto'), ('3Q', '3º Quarto'), ('4Q', '4º Quarto'), ('EX', 'Período Extra')], default='1Q', max_length=2, verbose_name='Periodo de Jogo'),
        ),
    ]
