# Generated by Django 3.2.5 on 2021-07-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Escala',
                'verbose_name_plural': 'Escalas',
            },
        ),
        migrations.CreateModel(
            name='GrupoArbitragem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_grupo', models.CharField(max_length=250, verbose_name='Nome do Grupo')),
            ],
            options={
                'verbose_name': 'Grupo de Arbitragem',
                'verbose_name_plural': 'Grupos de Arbitragem',
            },
        ),
        migrations.CreateModel(
            name='PosicaoEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Posição')),
                ('sigla', models.CharField(max_length=20, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Posição da Arbitragem',
                'verbose_name_plural': 'Posições da Arbitragem',
            },
        ),
    ]
