# Generated by Django 3.2.5 on 2021-07-21 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arbitragem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoarbitragem',
            name='admins_grupo',
            field=models.ManyToManyField(related_name='admins_grupo', to=settings.AUTH_USER_MODEL, verbose_name='Administradores do Grupo'),
        ),
        migrations.AddField(
            model_name='grupoarbitragem',
            name='membros_grupo',
            field=models.ManyToManyField(related_name='membros_grupo', to=settings.AUTH_USER_MODEL, verbose_name='Membros do Grupo'),
        ),
        migrations.AddField(
            model_name='grupoarbitragem',
            name='requisicao_pendente',
            field=models.ManyToManyField(related_name='requisicao_pendente', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios com Requisicao Pendente'),
        ),
        migrations.AddField(
            model_name='escala',
            name='arbitro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Arbitro'),
        ),
        migrations.AddField(
            model_name='escala',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogos.partida', verbose_name='Partida'),
        ),
        migrations.AddField(
            model_name='escala',
            name='posicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arbitragem.posicaoescala', verbose_name='Posicao'),
        ),
    ]
