# Generated by Django 3.2.5 on 2021-07-21 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arbitragem', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escala',
            options={'verbose_name': 'Escala', 'verbose_name_plural': 'Escalas'},
        ),
        migrations.AlterModelOptions(
            name='grupoarbitragem',
            options={'verbose_name': 'Grupo de Arbitragem', 'verbose_name_plural': 'Grupos de Arbitragem'},
        ),
        migrations.AlterModelOptions(
            name='posicaoescala',
            options={'verbose_name': 'Posicao da Arbitragem', 'verbose_name_plural': 'Posicoes da Arbitragem'},
        ),
    ]
